config/routes.rb
Rails.application.routes.draw do
  ################################################################################
  # Root

  root to: 'home#index'

  ################################################################################
  # API

  namespace :api do
    namespace :v2 do
      resources :rubygems, param: :name, only: [], constraints: { name: Patterns::ROUTE_PATTERN } do
        resources :versions, param: :number, only: :show, constraints: {
          number: /#{Gem::Version::VERSION_PATTERN}(?=\.(json|yaml|sha256)\z)|#{Gem::Version::VERSION_PATTERN}/o
        } do
          resources :contents, only: :index, constraints: {
            version_number: /#{Gem::Version::VERSION_PATTERN}/o,
            format: /json|yaml|sha256/
          }
        end
      end
    end

    namespace :v1 do
      resource :api_key, only: %i[show create update] do
        collection do
          post :revoke, to: "github_secret_scanning#revoke", defaults: { format: :json }
        end
      end
      resource :multifactor_auth, only: :show
      resource :webauthn_verification, only: :create do
        get ':webauthn_token/status', action: :status, as: :status, constraints: { format: :json }
      end
      resources :profiles, only: :show
      get "profile/me", to: "profiles#me"
      resources :downloads, only: :index do
        get :top, on: :collection
        get :all, on: :collection
      end
      constraints id: Patterns::ROUTE_PATTERN, format: /json|yaml/ do
        get 'owners/:handle/gems',
          to: 'owners#gems',
          as: 'owners_gems',
          constraints: { handle: Patterns::ROUTE_PATTERN },
          format: true

        resources :downloads, only: :show, format: true

        resources :versions, only: :show, format: true do
          member do
            get :reverse_dependencies, format: true
            get 'latest',
              to: 'versions#latest',
              as: 'latest',
              format: true,
              constraints: { format: /json|js/ }
          end

          resources :downloads,
            only: [:index],
            controller: 'versions/downloads',
            format: true do
            collection do
              get :search, format: true
            end
          end
        end
      end

      resources :dependencies,
        only: [:index],
        format: /marshal|json/,
        defaults: { format: 'marshal' }

      # for handling preflight request
      match '/gems/:id' => "rubygems#show", via: :options

      resources :rubygems,
        path: 'gems',
        only: %i[create show index],
        id: Patterns::LAZY_ROUTE_PATTERN,
        format: /json|yaml/ do
        member do
          get :reverse_dependencies
        end
        collection do
          delete :yank, to: "deletions#create"
        end
        constraints rubygem_id: Patterns::ROUTE_PATTERN do
          resource :owners, only: %i[show create edit update destroy]
          resources :trusted_publishers, controller: 'oidc/rubygem_trusted_publishers', only: %i[index create destroy show]
        end
      end

      resources :attestations, only: :show, format: /json/,
        constraints: { id: Patterns::ROUTE_PATTERN }

      resource :activity, only: [], format: /json|yaml/ do
        collection do
          get :latest
          get :just_updated
        end
      end

      resource :search, only: :show do
        get :autocomplete
      end

      resources :web_hooks, only: %i[create index] do
        collection do
          delete :remove
          post :fire
          post :hook_relay_report, to: 'hook_relay#report', defaults: { format: :json }
        end
      end

      resources :timeframe_versions, only: :index

      namespace :oidc do
        post 'trusted_publisher/exchange_token'
        resources :api_key_roles, only: %i[index show], param: :token, format: 'json', defaults: { format: :json } do
          member do
            post :assume_role
          end
        end

        resources :providers, only: %i[index show], format: 'json', defaults: { format: :json }

        resources :id_tokens, only: %i[index show], format: 'json', defaults: { format: :json }
      end
    end
  end

  get '/versions' => 'api/compact_index#versions'
  get '/info/:gem_name' => 'api/compact_index#info', as: :info,
      constraints: { gem_name: Patterns::ROUTE_PATTERN }
  get '/names' => 'api/compact_index#names'
  ################################################################################
  # API v0

  scope controller: 'api/deprecated', action: 'index' do
    get 'api_key'
    put 'api_key/reset'
    put 'api/v1/gems/unyank'
    put 'api/v1/api_key/reset'

    post 'gems'
    get 'gems/:id.json'

    scope path: 'gems/:rubygem_id' do
      put 'migrate'
      post 'migrate'
    end
  end

  ################################################################################
  # UI
  scope constraints: { format: :html }, defaults: { format: 'html' } do
    resource :search, only: :show do
      get :advanced
    end
    resource :dashboard, only: :show, constraints: { format: /html|atom/ }
    resources :subscriptions, only: :index
    resources :profiles, only: :show
    get "profile/me", to: "profiles#me", as: :my_profile
    resource :multifactor_auth, only: %i[update] do
      get 'recovery'
      post 'otp_update', to: 'multifactor_auths#otp_update', as: :otp_update
      post 'webauthn_update', to: 'multifactor_auths#webauthn_update', as: :webauthn_update
    end
    resource :totp, only: %i[new create destroy]
    resource :settings, only: :edit
    resource :profile, only: %i[edit update] do
      get :security_events
      member do
        get :delete
        delete :destroy, as: :destroy
      end

      resources :api_keys do
        delete :reset, on: :collection
      end

      namespace :oidc do
        resources :api_key_roles, param: :token do
          member do
            get 'github_actions_workflow'
          end
        end
        resources :api_key_roles, param: :token, only: %i[show], constraints: { format: :json }
        resources :id_tokens, only: %i[index show]
        resources :providers, only: %i[index show]
        resources :pending_trusted_publishers, except: %i[show edit update]
      end
    end
    resources :stats, only: :index
    get "/news" => 'news#show', as: 'legacy_news_path'
    resource :news, path: 'releases', only: [:show] do
      get :popular, on: :collection
    end
    resource :notifier, only: %i[update show]

    resources :rubygems,
      only: %i[index show],
      path: 'gems',
      constraints: { id: Patterns::ROUTE_PATTERN, format: /html|atom/ } do
      get :security_events, on: :member

      resource :subscription,
        only: %i[create destroy],
        constraints: { format: :js },
        defaults: { format: :js }
      resources :versions, only: %i[show index] do
        get '/dependencies', to: 'dependencies#show', constraints: { format: /json|html/ }
      end
      resources :reverse_dependencies, only: %i[index]
      resources :owners, only: %i[index destroy edit update create], param: :handle do
        get 'confirm', to: 'owners#confirm', as: :confirm, on: :collection
        get 'resend_confirmation', to: 'owners#resend_confirmation', as: :resend_confirmation, on: :collection
      end
      resources :trusted_publishers, controller: 'oidc/rubygem_trusted_publishers', only: %i[index create destroy new]
    end

    resources :webauthn_credentials, only: :destroy
    resource :webauthn_verification, only: [] do
      get 'successful_verification'
      get 'failed_verification'
      get ':webauthn_token', to: 'webauthn_verifications#prompt', as: ''
    end

    ################################################################################
    # Clearance Overrides and Additions

    resource :email_confirmations, only: %i[new create] do
      get 'confirm', to: 'email_confirmations#update', as: :update
      post 'otp_update', to: 'email_confirmations#otp_update', as: :otp_update
      post 'webauthn_update', to: 'email_confirmations#webauthn_update', as: :webauthn_update
      patch 'unconfirmed'
    end

    resource :password, only: %i[new create edit update] do
      post 'otp_edit', to: 'passwords#otp_edit', as: :otp_edit
      post 'webauthn_edit', to: 'passwords#webauthn_edit', as: :webauthn_edit
    end

    resource :session, only: %i[create destroy] do
      post 'otp_create', to: 'sessions#otp_create', as: :otp_create
      post 'webauthn_create', to: 'sessions#webauthn_create', as: :webauthn_create
      post 'webauthn_full_create', to: 'sessions#webauthn_full_create', as: :webauthn_full_create
      get 'verify', to: 'sessions#verify', as: :verify
      post 'authenticate', to: 'sessions#authenticate', as: :authenticate
      post 'webauthn_authenticate', to: 'sessions#webauthn_authenticate', as: :webauthn_authenticate

      get 'development_log_in_as/:user_id', to: 'sessions#development_log_in_as' if Gemcutter::ENABLE_DEVELOPMENT_LOG_IN
    end

    resources :users, only: %i[new create]

    get '/sign_in' => 'sessions#new', as: 'sign_in'
    delete '/sign_out' => 'sessions#destroy', as: 'sign_out'

    get '/sign_up' => 'users#new', as: 'sign_up' if Clearance.configuration.allow_sign_up?

    namespace :organizations, as: :organization do
      get "onboarding", to: redirect("/organizations/onboarding/name")
      delete "onboarding", to: "onboarding#destroy"

      namespace :onboarding do
        get "name", to: "name#new"
        post "name", to: "name#create"

        get "gems", to: "gems#edit"
        patch "gems", to: "gems#update"

        get "users", to: "users#edit"
        patch "users", to: "users#update"

        get "confirm", to: "confirm#edit"
        patch "confirm", to: "confirm#update"
      end
    end
    resources :organizations, only: %i[index show edit update], constraints: { id: Patterns::ROUTE_PATTERN } do

app/controllers/api/v1/api_keys_controller.rb
class Api::V1::ApiKeysController < Api::BaseController
  include ApiKeyable

  def show
    authenticate_or_request_with_http_basic do |username, password|
      # strip username mainly to remove null bytes
      user = User.authenticate(username.strip, password)
      check_mfa(user) do
        key = generate_unique_rubygems_key
        api_key = user.api_keys.build(legacy_key_defaults.merge(hashed_key: hashed_key(key)))

        save_and_respond(api_key, key)
      end
    end
  end

  def create
    authenticate_or_request_with_http_basic do |username, password|
      user = User.authenticate(username, password)

      check_mfa(user) do
        key = generate_unique_rubygems_key
        build_params = { owner: user, hashed_key: hashed_key(key), **api_key_create_params }
        api_key = ApiKey.new(build_params)

        save_and_respond(api_key, key)
      end
    end
  end

  def update
    authenticate_or_request_with_http_basic do |username, password|
      user = User.authenticate(username, password)

      check_mfa(user) do
        api_key = user.api_keys.find_by!(hashed_key: hashed_key(key_param))

        if api_key.update(api_key_update_params(api_key))
          respond_with "Scopes for the API key #{api_key.name} updated"
        else
          errors = api_key.errors.full_messages
          respond_with "Failed to update scopes for the API key #{api_key.name}: #{errors}", status: :unprocessable_entity
        end
      end
    end
  end

  private

  def check_mfa(user)
    if user&.mfa_gem_signin_authorized?(otp)
      if user.mfa_required_not_yet_enabled?
        render_forbidden t("multifactor_auths.api.mfa_required_not_yet_enabled").chomp
      elsif user.mfa_required_weak_level_enabled?
        render_forbidden t("multifactor_auths.api.mfa_required_weak_level_enabled").chomp
      else
        yield
      end
    elsif user&.mfa_enabled?
      prompt_text = otp.present? ? t(:otp_incorrect) : t(:otp_missing)
      render plain: prompt_text, status: :unauthorized
    else
      false
    end
  end

  def save_and_respond(api_key, key)
    if api_key.errors.blank? && api_key.save
      Mailer.api_key_created(api_key.id).deliver_later
      respond_with key
    else
      respond_with api_key.errors.full_messages.to_sentence, status: :unprocessable_entity
    end
  end

  def respond_with(msg, status: :ok)
    respond_to do |format|
      format.any(:all) { render plain: msg, status: status }
      format.json { render json: { rubygems_api_key: msg, status: status } }
      format.yaml { render plain: { rubygems_api_key: msg, status: status }.to_yaml }
    end
  end

  def otp
    request.headers["HTTP_OTP"]
  end

  def key_param
    params.expect(:api_key)
  end

  def api_key_create_params
    ApiKeysHelper.api_key_params(params.permit(:name, *ApiKey::API_SCOPES, :mfa, :rubygem_name, :expires_at, scopes: [ApiKey::API_SCOPES]))
  end

  def api_key_update_params(key)
    ApiKeysHelper.api_key_params(params.permit(*ApiKey::API_SCOPES, :mfa, scopes: [ApiKey::API_SCOPES]), key)
  end
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_action :disable_cache, only: :index
  before_action :set_page, only: :index

  include ApiKeyable

  include SessionVerifiable
  verify_session_before

  def index
    @api_key  = session.delete(:api_key)
    @api_keys = current_user.api_keys.unexpired.not_oidc.preload(ownership: :rubygem).page(@page)
    redirect_to new_profile_api_key_path if @api_keys.empty?
  end

  def new
    @api_key = current_user.api_keys.build
  end

  def edit
    @api_key = current_user.api_keys.find(params[:id])
    return unless @api_key.soft_deleted?

    flash[:error] = t(".invalid_key")
    redirect_to profile_api_keys_path
  end

  def create
    key = generate_unique_rubygems_key
    build_params = { owner: current_user, hashed_key: hashed_key(key), **api_key_create_params }
    @api_key = ApiKey.new(build_params)

    if @api_key.errors.present?
      flash.now[:error] = @api_key.errors.full_messages.to_sentence
      @api_key = current_user.api_keys.build(api_key_create_params.merge(rubygem_id: nil))
      return render :new
    end

    if @api_key.save
      Mailer.api_key_created(@api_key.id).deliver_later

      session[:api_key] = key
      redirect_to profile_api_keys_path, flash: { notice: t(".success") }
    else
      flash.now[:error] = @api_key.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    @api_key = current_user.api_keys.find(params[:id])
    @api_key.assign_attributes(api_key_update_params(@api_key))

    if @api_key.errors.present?
      flash.now[:error] = @api_key.errors.full_messages.to_sentence
      return render :edit
    end

    if @api_key.save
      redirect_to profile_api_keys_path, flash: { notice: t(".success") }
    else
      flash.now[:error] = @api_key.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    api_key = current_user.api_keys.find(params[:id])

    if api_key.expire!
      flash[:notice] = t(".success", name: api_key.name)
    else
      flash[:error] = api_key.errors.full_messages.to_sentence
    end
    redirect_to profile_api_keys_path
  end

  def reset
    if current_user.api_keys.expire_all!
      flash[:notice] = t(".success")
    else
      flash[:error] = t("try_again")
    end
    redirect_to profile_api_keys_path
  end

  private

  def verify_session_redirect_path
    case action_name
    when "reset", "destroy"
      profile_api_keys_path
    when "create"
      new_profile_api_key_path
    when "update"
      edit_profile_api_key_path(params[:id])
    else
      super
    end
  end

  def api_key_create_params
    ApiKeysHelper.api_key_params(params.expect(api_key: [:name, *ApiKey::API_SCOPES, :mfa, :rubygem_id, :expires_at]))
  end

  def api_key_update_params(existing_api_key = nil)
    ApiKeysHelper.api_key_params(
      params.expect(api_key: [*ApiKey::API_SCOPES, :mfa, :rubygem_id, scopes: ApiKey::API_SCOPES]), existing_api_key
    )
  end
end

app/controllers/avo/api_keys_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::ApiKeysController < Avo::ResourcesController
end

app/helpers/api_keys_helper.rb
module ApiKeysHelper
  def gem_scope(api_key)
    return invalid_gem_tooltip(api_key.soft_deleted_rubygem_name) if api_key.soft_deleted_by_ownership?

    api_key.rubygem ? api_key.rubygem.name : t("api_keys.all_gems")
  end

  def api_key_checkbox(form, api_scope)
    exclusive = ApiKey::EXCLUSIVE_SCOPES.include?(api_scope)
    gem_scope = ApiKey::APPLICABLE_GEM_API_SCOPES.include?(api_scope)

    data = {}
    data[:exclusive_checkbox_target] = exclusive ? "exclusive" : "inclusive"
    data[:gem_scope_target] = "checkbox" if gem_scope

    html_options = { class: "form__checkbox__input", id: api_scope, data: }
    form.check_box api_scope, html_options, "true", "false"
  end

  def self.api_key_params(params, existing_api_key = nil)
    scopes = params.fetch(:scopes, existing_api_key&.scopes || []).to_set
    boolean = ActiveRecord::Type::Boolean.new
    ApiKey::API_SCOPES.each do |scope|
      next unless params.key?(scope)

      if boolean.cast(params.delete(scope))
        scopes << scope
      else
        scopes.delete(scope)
      end
    end
    params[:scopes] = scopes.sort
    params
  end

  private

  def invalid_gem_tooltip(name)
    content_tag(
      :span,
      "#{name} [?]",
      class: "tooltip__text",
      data: { tooltip: t("api_keys.gem_ownership_removed", rubygem_name: name) }
    )
  end
end

app/views/api_keys/_form.html.erb
<%= form_with model: [:profile, @api_key], data: { controller: "exclusive-checkbox gem-scope" } do |f| %>
  <%= label_tag :name, t("api_keys.index.name"), class: "form__label" %>
  <%= f.text_field :name, class: "form__input", autocomplete: :off, disabled: f.object.persisted? %>

  <div class="form__group">
    <%= label_tag :scope, t(".exclusive_scopes"), class: "form__label" %>
    <% ApiKey::EXCLUSIVE_SCOPES.each do |api_scope| %>
      <div class = "form__checkbox__item">
        <%= api_key_checkbox(f, api_scope) %>
        <%= label_tag api_scope, t("api_keys.index.#{api_scope}"), class: "form__checkbox__label" %>
      </div>
    <% end %>
  </div>
  <div class="form__group">
    <%= label_tag :scope, t("api_keys.index.scopes"), class: "form__label" %>
    <% (ApiKey::API_SCOPES - ApiKey::EXCLUSIVE_SCOPES).each do |api_scope| %>
      <div class = "form__checkbox__item">
        <%= api_key_checkbox(f, api_scope) %>
        <%= label_tag api_scope, t("api_keys.index.#{api_scope}"), class: "form__checkbox__label" %>
      </div>
    <% end %>
  </div>

  <div class="form__group api_key_rubygem_id_form">
    <%= label_tag :rubygem_id, t(".rubygem_scope"), class: "form__label" %>
    <p><%= t(".rubygem_scope_info") %></p>
    <%= f.collection_select :rubygem_id, current_user.rubygems.by_name, :id, :name, { include_blank: t("api_keys.all_gems") }, selected: :rubygem_id, class: "form__input form__select", data: { gem_scope_target: "selector" } %>
  </div>

  <div class="form__group">
    <%= label_tag :expires_at, t(".expiration"), class: "form__label" %>
    <%= f.datetime_field :expires_at, min: 5.minutes.from_now, include_seconds: false, class: "form__input", disabled: f.object.persisted?  %>
  </div>

  <% unless current_user.mfa_disabled? || current_user.mfa_ui_and_api? %>
    <div class="form__group">
      <%= label_tag :mfa, t(".multifactor_auth"), class: "form__label" %>
      <div class="form__checkbox__item">
        <%= f.check_box :mfa, { class: "form__checkbox__input", id: :mfa, checked: true } , "true", "false" %>
        <%= label_tag :mfa, t(".enable_mfa"), class: "form__checkbox__label" %>
      </div>
    </div>
  <% end %>

  <%= f.submit class: "form__submit" %>
<% end %>

app/views/api_keys/edit.html.erb
<% @title = t(".edit_api_key") %>

<div class="t-body">
  <%= render "form", api_key: @api_key %>
</div>

app/views/api_keys/index.html.erb
<% @title = t(".api_keys") %>

<% if @api_key %>
  <div class="t-body push--bottom-s">
    <p>
      <%= t(".save_key") %>
      <span> <code><%= @api_key %></code> </span>
    </p>
  </div>
<% end %>

<header class="gems__header">
  <p class="gems__meter">
    <%= page_entries_info @api_keys, entry_name: 'API keys' %>
  </p>
</header>

<div class="t-body">
  <table class="owners__table">
    <tr class="owners__row owners__header">
      <th class="owners__cell">
        <%= t(".name") %>
      </th>
      <th class="owners__cell">
        <%= t(".scopes") %>
      </th>
      <th class="owners__cell">
        <%= t(".gem") %>
      </th>
      <th class="owners__cell">
        <%= t(".age") %>
      </th>
      <% if current_user.mfa_enabled? %>
        <th class="owners__cell">
          <%= t(".mfa") %>
        </th>
      <% end %>
      <th class="owners__cell">
        <%= t(".last_access") %>
      </th>
      <th class="owners__cell">
        <%= t(".expiration") %>
      </th>
      <th class="owners__cell">
      </th>
      <th class="owners__cell">
      </th>
    </tr>

    <% for api_key in @api_keys do %>
      <tr class="owners__row <%= 'owners__row__invalid' if api_key.soft_deleted? %>">
        <td class="owners__cell" data-title="Name">
          <%= api_key.name %>
        </td>
        <td class="owners__cell" data-title="Scopes">
          <% api_key.scopes.each do |scope| %>
            <ul class="scopes__list"><%= t(".#{scope}") %></ul>
          <% end %>
        </td>
        <td class="owners__cell" data-title="Gem">
          <%= gem_scope(api_key) %>
        </td>
        <td class="owners__cell" data-title="Age">
          <%= time_ago_in_words(api_key.created_at) %>
        </td>
        <% if current_user.mfa_enabled? %>
          <td class="owners__cell" data-title="MFA">
            <%= image_tag("/images/check.svg") if api_key.mfa? %>
          </td>
        <% end %>
        <td class="owners__cell" data-title="Last access">
          <%= api_key.last_accessed_at&.strftime("%Y-%m-%d %H:%M %Z") %>
        </td>
        <td class="owners__cell" data-title="Expiration">
          <%= api_key.expires_at&.strftime("%Y-%m-%d %H:%M %Z") %>
        </td>
        <td class="owners__cell">
          <% unless api_key.soft_deleted? %>
            <%= button_to t("edit"),
                        edit_profile_api_key_path(id: api_key.id),
                        method: :get,
                        class: "form__submit form__submit--small" %>
          <% end %>
        </td>
        <td class="owners__cell">
          <%= button_to t(".delete"),
                      profile_api_key_path(id: api_key.id),
                      method: :delete,
                      class: "form__submit form__submit--small",
                      data: { confirm: t(".confirm")} %>
        </td>
      </tr>
    <% end %>

    <tr class="owners__row">
      <td class="owners__cell">
      </td>
      <td class="owners__cell">
      </td>
      <td class="owners__cell">
      </td>
      <td class="owners__cell">
      </td>
      <td class="owners__cell">
      </td>
      <td class="owners__cell">
      </td>
      <td class="owners__cell">
      </td>
      <% if current_user.mfa_enabled? %>
        <td class="owners__cell">
        </td>
      <% end %>
      <td class="owners__cell">
        <%= button_to t(".reset"),
                    reset_profile_api_keys_path,
                    method: :delete,
                    class: "form__submit form__submit--small",
                    data: { confirm: t(".confirm_all")} %>
      </td>
    </tr>
  </table>

  <%= paginate @api_keys %>

  <p><%= button_to t(".new_key"), new_profile_api_key_path, method: "get", class: "form__submit" %></p>
  <% if current_user.oidc_api_key_roles.any? %>
    <h2 class="t-display"><%= link_to t("oidc.api_key_roles.index.api_key_roles"), profile_oidc_api_key_roles_path, class: "t-link t-underline" %> →</h2>
  <% end %>
</div>

app/views/api_keys/new.html.erb
<% @title = t(".new_api_key") %>

<div class="t-body">
  <%= render "form", api_key: @api_key %>
</div>