config/routes.rb
Rails.application.routes.draw do
  ################################################################################
  # Root

  root to: 'home#index'

  ################################################################################
  # API

  namespace :api do
    namespace :v2 do
      resources :rubygems, param: :name, only: [], constraints: { name: Patterns::ROUTE_PATTERN } do
        resources :versions, param: :number, only: :show, constraints: {
          number: /#{Gem::Version::VERSION_PATTERN}(?=\.(json|yaml|sha256)\z)|#{Gem::Version::VERSION_PATTERN}/o
        } do
          resources :contents, only: :index, constraints: {
            version_number: /#{Gem::Version::VERSION_PATTERN}/o,
            format: /json|yaml|sha256/
          }
        end
      end
    end

    namespace :v1 do
      resource :api_key, only: %i[show create update] do
        collection do
          post :revoke, to: "github_secret_scanning#revoke", defaults: { format: :json }
        end
      end
      resource :multifactor_auth, only: :show
      resource :webauthn_verification, only: :create do
        get ':webauthn_token/status', action: :status, as: :status, constraints: { format: :json }
      end
      resources :profiles, only: :show
      get "profile/me", to: "profiles#me"
      resources :downloads, only: :index do
        get :top, on: :collection
        get :all, on: :collection
      end
      constraints id: Patterns::ROUTE_PATTERN, format: /json|yaml/ do
        get 'owners/:handle/gems',
          to: 'owners#gems',
          as: 'owners_gems',
          constraints: { handle: Patterns::ROUTE_PATTERN },
          format: true

        resources :downloads, only: :show, format: true

        resources :versions, only: :show, format: true do
          member do
            get :reverse_dependencies, format: true
            get 'latest',
              to: 'versions#latest',
              as: 'latest',
              format: true,
              constraints: { format: /json|js/ }
          end

          resources :downloads,
            only: [:index],
            controller: 'versions/downloads',
            format: true do
            collection do
              get :search, format: true
            end
          end
        end
      end

      resources :dependencies,
        only: [:index],
        format: /marshal|json/,
        defaults: { format: 'marshal' }

      # for handling preflight request
      match '/gems/:id' => "rubygems#show", via: :options

      resources :rubygems,
        path: 'gems',
        only: %i[create show index],
        id: Patterns::LAZY_ROUTE_PATTERN,
        format: /json|yaml/ do
        member do
          get :reverse_dependencies
        end
        collection do
          delete :yank, to: "deletions#create"
        end
        constraints rubygem_id: Patterns::ROUTE_PATTERN do
          resource :owners, only: %i[show create edit update destroy]
          resources :trusted_publishers, controller: 'oidc/rubygem_trusted_publishers', only: %i[index create destroy show]
        end
      end

      resources :attestations, only: :show, format: /json/,
        constraints: { id: Patterns::ROUTE_PATTERN }

      resource :activity, only: [], format: /json|yaml/ do
        collection do
          get :latest
          get :just_updated
        end
      end

      resource :search, only: :show do
        get :autocomplete
      end

      resources :web_hooks, only: %i[create index] do
        collection do
          delete :remove
          post :fire
          post :hook_relay_report, to: 'hook_relay#report', defaults: { format: :json }
        end
      end

      resources :timeframe_versions, only: :index

      namespace :oidc do
        post 'trusted_publisher/exchange_token'
        resources :api_key_roles, only: %i[index show], param: :token, format: 'json', defaults: { format: :json } do
          member do
            post :assume_role
          end
        end

        resources :providers, only: %i[index show], format: 'json', defaults: { format: :json }

        resources :id_tokens, only: %i[index show], format: 'json', defaults: { format: :json }
      end
    end
  end

  get '/versions' => 'api/compact_index#versions'
  get '/info/:gem_name' => 'api/compact_index#info', as: :info,
      constraints: { gem_name: Patterns::ROUTE_PATTERN }
  get '/names' => 'api/compact_index#names'
  ################################################################################
  # API v0

  scope controller: 'api/deprecated', action: 'index' do
    get 'api_key'
    put 'api_key/reset'
    put 'api/v1/gems/unyank'
    put 'api/v1/api_key/reset'

    post 'gems'
    get 'gems/:id.json'

    scope path: 'gems/:rubygem_id' do
      put 'migrate'
      post 'migrate'
    end
  end

  ################################################################################
  # UI
  scope constraints: { format: :html }, defaults: { format: 'html' } do
    resource :search, only: :show do
      get :advanced
    end
    resource :dashboard, only: :show, constraints: { format: /html|atom/ }
    resources :subscriptions, only: :index
    resources :profiles, only: :show
    get "profile/me", to: "profiles#me", as: :my_profile
    resource :multifactor_auth, only: %i[update] do
      get 'recovery'
      post 'otp_update', to: 'multifactor_auths#otp_update', as: :otp_update
      post 'webauthn_update', to: 'multifactor_auths#webauthn_update', as: :webauthn_update
    end
    resource :totp, only: %i[new create destroy]
    resource :settings, only: :edit
    resource :profile, only: %i[edit update] do
      get :security_events
      member do
        get :delete
        delete :destroy, as: :destroy
      end

      resources :api_keys do
        delete :reset, on: :collection
      end

      namespace :oidc do
        resources :api_key_roles, param: :token do
          member do
            get 'github_actions_workflow'
          end
        end
        resources :api_key_roles, param: :token, only: %i[show], constraints: { format: :json }
        resources :id_tokens, only: %i[index show]
        resources :providers, only: %i[index show]
        resources :pending_trusted_publishers, except: %i[show edit update]
      end
    end
    resources :stats, only: :index
    get "/news" => 'news#show', as: 'legacy_news_path'
    resource :news, path: 'releases', only: [:show] do
      get :popular, on: :collection
    end
    resource :notifier, only: %i[update show]

    resources :rubygems,
      only: %i[index show],
      path: 'gems',
      constraints: { id: Patterns::ROUTE_PATTERN, format: /html|atom/ } do
      get :security_events, on: :member

      resource :subscription,
        only: %i[create destroy],
        constraints: { format: :js },
        defaults: { format: :js }
      resources :versions, only: %i[show index] do
        get '/dependencies', to: 'dependencies#show', constraints: { format: /json|html/ }
      end
      resources :reverse_dependencies, only: %i[index]
      resources :owners, only: %i[index destroy edit update create], param: :handle do
        get 'confirm', to: 'owners#confirm', as: :confirm, on: :collection
        get 'resend_confirmation', to: 'owners#resend_confirmation', as: :resend_confirmation, on: :collection
      end
      resources :trusted_publishers, controller: 'oidc/rubygem_trusted_publishers', only: %i[index create destroy new]
    end

    resources :webauthn_credentials, only: :destroy
    resource :webauthn_verification, only: [] do
      get 'successful_verification'
      get 'failed_verification'
      get ':webauthn_token', to: 'webauthn_verifications#prompt', as: ''
    end

    ################################################################################
    # Clearance Overrides and Additions

    resource :email_confirmations, only: %i[new create] do
      get 'confirm', to: 'email_confirmations#update', as: :update
      post 'otp_update', to: 'email_confirmations#otp_update', as: :otp_update
      post 'webauthn_update', to: 'email_confirmations#webauthn_update', as: :webauthn_update
      patch 'unconfirmed'
    end

    resource :password, only: %i[new create edit update] do
      post 'otp_edit', to: 'passwords#otp_edit', as: :otp_edit
      post 'webauthn_edit', to: 'passwords#webauthn_edit', as: :webauthn_edit
    end

    resource :session, only: %i[create destroy] do
      post 'otp_create', to: 'sessions#otp_create', as: :otp_create
      post 'webauthn_create', to: 'sessions#webauthn_create', as: :webauthn_create
      post 'webauthn_full_create', to: 'sessions#webauthn_full_create', as: :webauthn_full_create
      get 'verify', to: 'sessions#verify', as: :verify
      post 'authenticate', to: 'sessions#authenticate', as: :authenticate
      post 'webauthn_authenticate', to: 'sessions#webauthn_authenticate', as: :webauthn_authenticate

      get 'development_log_in_as/:user_id', to: 'sessions#development_log_in_as' if Gemcutter::ENABLE_DEVELOPMENT_LOG_IN
    end

    resources :users, only: %i[new create]

    get '/sign_in' => 'sessions#new', as: 'sign_in'
    delete '/sign_out' => 'sessions#destroy', as: 'sign_out'

    get '/sign_up' => 'users#new', as: 'sign_up' if Clearance.configuration.allow_sign_up?

    namespace :organizations, as: :organization do
      get "onboarding", to: redirect("/organizations/onboarding/name")
      delete "onboarding", to: "onboarding#destroy"

      namespace :onboarding do
        get "name", to: "name#new"
        post "name", to: "name#create"

        get "gems", to: "gems#edit"
        patch "gems", to: "gems#update"

        get "users", to: "users#edit"
        patch "users", to: "users#update"

        get "confirm", to: "confirm#edit"
        patch "confirm", to: "confirm#update"
      end
    end
    resources :organizations, only: %i[index show edit update], constraints: { id: Patterns::ROUTE_PATTERN } do

app/controllers/api/v1/searches_controller.rb
class Api::V1::SearchesController < Api::BaseController
  before_action :set_page, only: %i[show autocomplete]
  before_action :verify_query_string, only: %i[show autocomplete]

  rescue_from ElasticSearcher::SearchNotAvailableError, with: :search_not_available_error
  rescue_from ElasticSearcher::InvalidQueryError, with: :render_bad_request

  def show
    @rubygems = ElasticSearcher.new(query_params, page: @page).api_search
    respond_to do |format|
      format.json { render json: @rubygems }
      format.yaml { render yaml: @rubygems }
    end
  end

  def autocomplete
    results = ElasticSearcher.new(query_params, page: @page).suggestions
    render json: results
  end

  private

  def verify_query_string
    render_bad_request unless query_params.is_a?(String)
  end

  def search_not_available_error(error)
    render plain: error.message, status: :service_unavailable
  end

  def query_params
    params.expect(:query)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action -> { set_page Gemcutter::SEARCH_MAX_PAGES }, only: :show

  def show
    return unless params[:query].is_a?(String)
    @error_msg, @gems = ElasticSearcher.new(params[:query], page: @page).search

    return unless @gems
    set_total_pages if @gems.total_count > Gemcutter::SEARCH_MAX_PAGES * Rubygem.default_per_page
    exact_match = Rubygem.name_is(params[:query]).first
    @yanked_gem = exact_match unless exact_match&.indexed_versions?
    @yanked_filter = true if params[:yanked] == "true"
  end

  def advanced
  end

  private

  def set_total_pages
    class << @gems
      def total_pages
        Gemcutter::SEARCH_MAX_PAGES
      end
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
  def es_suggestions(gems)
    return false if gems.size >= 1
    return false unless gems.respond_to?(:response)
    suggestions = gems.response["suggest"]
    return false if suggestions.blank?
    return false if suggestions["suggest_name"].blank?
    return false if suggestions["suggest_name"][0]["options"].empty?
    suggestions.map { |_k, v| v.first["options"] }.flatten.pluck("text").uniq
  end

  def aggregation_match_count(aggregration, field)
    count = aggregration["buckets"][field]["doc_count"]
    return unless count > 0

    path = search_path(params: { query: "#{field}:#{params[:query]}" })
    link_to "#{field.capitalize} (#{count})", path, class: "t-link--black"
  end

  def aggregation_count(aggregration, duration, buckets_pos)
    count = aggregration["buckets"][buckets_pos]["doc_count"]
    return unless count > 0

    time_ago = (Time.zone.today - duration).to_fs(:db)
    path = search_path(params: { query: "#{params[:query]} AND updated:[#{time_ago} TO *}" })
    update_info = (duration == 30.days ? t("searches.show.month_update", count: count) : t("searches.show.week_update", count: count))
    link_to update_info, path, class: "t-link--black"
  end

  def aggregation_yanked(yanked_gem)
    return unless yanked_gem

    path = search_path(params: { query: params[:query], yanked: true })
    link_to t("searches.show.yanked", count: 1), path, class: "t-link--black"
  end

  def not_empty?(response)
    response["hits"]["total"]["value"] != 0
  end
end

app/views/searches/_aggregations.html.erb
<% if gems.respond_to?(:response) && aggregations = gems.response['aggregations'] %>
  <div class="aggregations">
    <%= t('searches.show.filter') if not_empty?(gems.response) %>
    <%= aggregation_match_count aggregations['matched_field'], 'name' %>
    <%= aggregation_match_count aggregations['matched_field'], 'description' %>
    <%= aggregation_match_count aggregations['matched_field'], 'summary' %>
    <%= aggregation_count aggregations['date_range'], 7.days, 1 %>
    <%= aggregation_count aggregations['date_range'], 30.days, 0 %>
    <%= aggregation_yanked @yanked_gem %>
  </div>
<% end %>

app/views/searches/advanced.html.erb
<% @title = t("advanced_search") %>

<div class="home__search-wrap" role="search" data-controller="search">
  <%= form_tag search_url, id: "advanced-search", method: :get do %>
    <%= search_field_tag(
      :query,
      params[:query],
      placeholder: t("layouts.application.header.search_gem_html"),
      autofocus: current_page?(root_url),
      id: "query",
      class: "home__search",
      data: { search_target: "query" }
    ) %>
    <%= label_tag :query do %>
      <span class="t-hidden"><%= t("layouts.application.header.search_gem_html") %></span>
    <% end %>
    <%= submit_tag "⌕", id: "advanced_search_submit", name: nil, class: "home__search__icon" %>
  <% end %>

  <dl class="search-fields">
    <dt><%= label_tag :name, t(".name"), class: "form__label" %></dt>
    <dd><%= text_field_tag :name, "", placeholder: "active OR action", class: "form__input", data: { search_target: "attribute", action: "input->search#input keydown.enter->search#submit" } %></dd>

    <dt><%= label_tag :summary, t(".summary"), class: "form__label" %></dt>
    <dd><%= text_field_tag :summary, "", placeholder: "ORM, NoSQL", class: "form__input", data: { search_target: "attribute", action: "input->search#input keydown.enter->search#submit" } %></dd>

    <dt><%= label_tag :description, t(".description"), class: "form__label" %></dt>
    <dd><%= text_field_tag :description, "", placeholder: "associations AND validations", class: "form__input", data: { search_target: "attribute", action: "input->search#input keydown.enter->search#submit" } %></dd>

    <dt><%= label_tag :downloads, t(".downloads"), class: "form__label" %></dt>
    <dd><%= text_field_tag :downloads, "", placeholder: ">20000", class: "form__input", pattern: "\\s*(<=?|>=?)?[\\d]+\\s*", data: { search_target: "attribute", action: "input->search#input keydown.enter->search#submit" } %></dd>

    <dt><%= label_tag :updated, t(".updated"), class: "form__label" %></dt>
    <dd><%= text_field_tag :updated, "", placeholder: ">#{1.week.ago.strftime('%F')}", class: "form__input", pattern: "\\s*(<=?|>=?)?[\\d-]+\\s*", data: { search_target: "attribute", action: "input->search#input keydown.enter->search#submit" } %></dd>
  </dl>
</div>

app/views/searches/show.html.erb
<% @title = "search" %>

<% if @error_msg %>
  <div class="errorExplanation">
    <p><%= @error_msg %></p>
  </div>
<% end %>
<%= link_to t("advanced_search"), advanced_search_path, class: "t-link--gray t-link--has-arrow" %>
<% if @yanked_filter %>
  <% @subtitle = t('.subtitle_html', :query => params[:query]) %>

  <% if @yanked_gem.present? %>
    <%= link_to rubygem_path(@yanked_gem.slug), :class => 'gems__gem' do %>
      <span class="gems__gem__info">
        <h2 class="gems__gem__name">
          <%= @yanked_gem.name %>
          <span class="gems__gem__badge"><%= t('searches.advanced.yanked') %></span>
        </h2>
        <p class="gems__gem__desc t-text"><%= t('rubygems.show_yanked.not_hosted_notice') %></p>
      </span>
    <% end %>
  <% end %>
<% else %>
  <% if @gems %>
    <% @subtitle = t('.subtitle_html', :query => params[:query]) %>

    <header class="gems__header push--s">
      <p class="gems__meter"><%= page_entries_info(@gems, :entry_name => 'gem') %></p>
    </header>

    <%= render partial: 'aggregations', locals: { gems: @gems } %>

    <% suggestions = es_suggestions(@gems) %>
    <% if suggestions %>
      <div class='search__suggestions'>
        <p>
          <%= t(".suggestion") %>
          <%= to_sentence(suggestions.map do |term|
            link_to term, search_path(params: { query: term }), only_path: true
          end, last_word_connector: ' or ') %>?
        </p>
      </div>
    <% end %>

    <% if @gems.present? %>
      <%= render partial: 'rubygems/rubygem', collection: @gems %>
      <%= paginate @gems %>
    <% end %>
  <% end %>
<% end %>